training:
  lr: 0.0005 #5e-4
  lr_decay_interval: 200
  lr_decay_factor: 0.2
  grad_clip: null
  npoints_decoder: 1000
  ckpt: null
  batch_size: 64
  pc_samples: 300
mode:
  noisy_obs: null
encoder:
  type: 'airnet'
  encoder_attn_dim: 256
  npoints_per_layer: [300, 150, 50]
  encoder_nneigh: 16
  encoder_nneigh_reduced: 12
  nfinal_trans: 3
  encoder_attn_dim_reduced: 200
decoder:
  type: 'airnet'
  decoder_attn_dim: 200
  decoder_nneigh: 6
  decoder_hidden_dim: 64
  decoder_nblocks: 5
