training:
  lr: 0.0001
  lr_decay_interval: null
  lr_decay_factor: null
  grad_clip: null
  npoints_decoder: 2000
  ckpt: null
  batch_size: 20
  pc_samples: 3000
mode:
  noisy_obs: null
encoder:
  type: 'ifnet'
decoder:
  type: 'ifnet'

